### ISSUE TITLE
How is parseerror-eq licensed?

### ISSUE THREAD

**Issue by RyanGlScott** [stackbuilders/parseerror-eq#2]
The [documentation for `Text.ParseErrorEq`](https://github.com/stackbuilders/parseerror-eq/blob/ad750e9c23bc2007cd4b09d00bf72aea8d262c47/src/Text/ParseErrorEq.hs#L7) claims that this is GPL-3–licensed, yet [the `.cabal` file](https://github.com/stackbuilders/parseerror-eq/blob/ad750e9c23bc2007cd4b09d00bf72aea8d262c47/parseerror-eq.cabal#L27) claims that this is MIT-licensed. Which one is accurate?

**Comment by jsl** [comment]
Hi @RyanGlScott, sorry about the confusion! License is MIT. I just changed the GPL reference you mentioned and pushed to master. Thanks very much for pointing this out, and please re-open if you have any other concerns regarding licensing.
